source-file ~/.tmux.colors.conf
set -g prefix 'C-q'
set -g default-terminal "rxvt-unicode-256color"

setw -g mode-keys vi
set -s escape-time 0

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind Tab choose-tree -GZ
unbind w
bind "'" choose-tree -Zs
unbind s
unbind C-z

set -g set-titles on
set -g set-titles-string "#W"

unbind %
bind | split-window -h -c '#{pane_current_path}'
unbind '"'
bind - split-window -v -c '#{pane_current_path}'
unbind c
bind + new-window -c '#{pane_current_path}'
bind-key Space send-keys -R \; clear-history \; send-keys 'C-l'

set -g base-index 1
setw -g pane-base-index 1

# aliases
bind r source-file ~/.tmux.conf \; display "Reloading configs..."

# mouse ON
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
