#!/usr/bin/env bash

function active {
    socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | \
      stdbuf -o0 grep -E '^(submap>>)' | \
      stdbuf -o0 awk -F '>>|,' '{ if ($0 ~ /^submap>>/) { print $2 } }'
}

if [[ $1 == '--active' ]]; then active; fi
