preload = /home/samflores/Pictures/Wallpapers/hollow-knight.jpg

wallpaper = eDP-1,/home/samflores/Pictures/Wallpapers/hollow-knight.jpg
wallpaper = HDMI-A-1,/home/samflores/Pictures/Wallpapers/hollow-knight.jpg
# wallpaper = DP-10,/home/samflores/Pictures/Wallpapers/hollow-knight.jpg

splash = false

# ipc = off
