preload = /home/samflores/Pictures/Wallpapers/checkerboard.png

wallpaper = DP-1,/home/samflores/Pictures/Wallpapers/checkerboard.png
wallpaper = HDMI-A-1,/home/samflores/Pictures/Wallpapers/checkerboard.png
wallpaper = HDMI-A-2,/home/samflores/Pictures/Wallpapers/checkerboard.png

splash = false

# ipc = off
