source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/exec.conf
source = ~/.config/hypr/modules/monitor.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/appearance.conf
source = ~/.config/hypr/modules/layouts.conf
source = ~/.config/hypr/modules/rules.conf
source = ~/.config/hypr/modules/bindings.conf
