preload = /home/samflores/Pictures/Wallpapers/deep_jump.png

wallpaper = eDP-1,/home/samflores/Pictures/Wallpapers/deep_jump.png
wallpaper = DP-9,/home/samflores/Pictures/Wallpapers/deep_jump.png
wallpaper = DP-10,/home/samflores/Pictures/Wallpapers/deep_jump.png

splash = false

# ipc = off
