# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▄▀█ █▀▀ █▄░█ ▀█▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █░▀░█ █▀█ █░▀█ █▀█ █▄█ █░▀░█ ██▄ █░▀█ ░█░
bind = SUPER, X, killactive,
bind = SUPER SHIFT, Q, exit,
bind = SUPER, F, fullscreen,
bind = SUPER, Y, togglefloating,

# █▀▀ █▀█ █▀▀ █░█ █▀
# █▀░ █▄█ █▄▄ █▄█ ▄█
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
# bind = SUPER SHIFT, Equal, layoutmsg, addmaster
# bind = SUPER SHIFT, Minus, layoutmsg, removemaster
# bind = SUPER SHIFT, bracketleft, layoutmsg, orientationleft
# bind = SUPER SHIFT, bracketright, layoutmsg, orientationright

# █▀▄▀█ █▀█ █░█ █▀▀
# █░▀░█ █▄█ ▀▄▀ ██▄
# bind = SUPER SHIFT, j, layoutmsg, swapnext
# bind = SUPER SHIFT, k, layoutmsg, swapprev
bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, l, movewindow, r
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, j, movewindow, d
bind = SUPER SHIFT, R, layoutmsg, movetoroot
bind = SUPER SHIFT, S, layoutmsg, swapsplit

# █▀█ █▀▀ █▀ █ ▀█ █▀▀
# █▀▄ ██▄ ▄█ █ █▄ ██▄
bind = SUPER CTRL, h, resizeactive, -20 0
bind = SUPER CTRL, l, resizeactive, 20 0
bind = SUPER CTRL, k, resizeactive, 0 -20
bind = SUPER CTRL, j, resizeactive, 0 20

# ▀█▀ ▄▀█ █▄▄ █▄▄ █▀▀ █▀▄
# ░█░ █▀█ █▄█ █▄█ ██▄ █▄▀
bind= SUPER CTRL, Tab, changegroupactive
bind = SUPER, G, submap, group

bind = SUPER, S, submap, split
submap = split
bind = , j, layoutmsg, preselect d
bind = , j, submap, reset
bind = , k, layoutmsg, preselect u
bind = , k, submap, reset
bind = , h, layoutmsg, preselect l
bind = , h, submap, reset
bind = , l, layoutmsg, preselect r
bind = , l, submap, reset
bind = , escape, submap, reset
submap=reset

submap = group
bind = , g, togglegroup
bind = , g, submap, reset
bind = , j, moveintogroup, d
bind = , j, submap, reset
bind = , k, moveintogroup, u
bind = , k, submap, reset
bind = , h, moveintogroup, l
bind = , h, submap, reset
bind = , l, moveintogroup, r
bind = , l, submap, reset
bind = , escape, submap, reset
submap=reset

bind = SUPER, bracketright, layoutmsg, move +col
bind = SUPER, bracketleft, layoutmsg, move -col
bind = SUPER SHIFT, bracketright, layoutmsg, movewindowto r
bind = SUPER SHIFT, bracketleft, layoutmsg, movewindowto l
bind = SUPER SHIFT, up, layoutmsg, movewindowto u
bind = SUPER SHIFT, down, layoutmsg, movewindowto d
