# █▀▀ █▀▀ █▄░█ █▀▀ █▀█ ▄▀█ █░░
# █▄█ ██▄ █░▀█ ██▄ █▀▄ █▀█ █▄▄
general {
  gaps_in=3
  gaps_out=3
  border_size=0
  no_border_on_floating = true
  layout = dwindle
}

# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vrr = 1
  enable_swallow = true
  swallow_regex = ^(wezterm)$
}

cursor {
  inactive_timeout = 3
}

# █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█
decoration {
  # █▀█ █▀█ █░█ █▄░█ █▀▄   █▀▀ █▀█ █▀█ █▄░█ █▀▀ █▀█
  # █▀▄ █▄█ █▄█ █░▀█ █▄▀   █▄▄ █▄█ █▀▄ █░▀█ ██▄ █▀▄
  rounding = 6

  # █▀█ █▀█ ▄▀█ █▀▀ █ ▀█▀ █▄█
  # █▄█ █▀▀ █▀█ █▄▄ █ ░█░ ░█░
  active_opacity = 1.0
  inactive_opacity = 0.75

  # █▄▄ █░░ █░█ █▀█
  # █▄█ █▄▄ █▄█ █▀▄
  blur {
    enabled = true
    size = 7
    passes = 3
  }

  # █▀ █░█ ▄▀█ █▀▄ █▀█ █░█░█
  # ▄█ █▀█ █▀█ █▄▀ █▄█ ▀▄▀▄▀
  shadow {
    enabled = true
    ignore_window = true
    offset = 2 2
    range = 4
    render_power = 2
    color = 0x66000000
  }
}

animations {
  enabled=1
  bezier=easeOutSine, 0.39, 0.575, 0.565, 1
  animation=windows,1,2,easeOutSine,popin
  animation=fade,1,2,easeOutSine
  animation=workspaces,1,2,easeOutSine,slidefade 20%
}
