# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀

source = ~/.config/hypr/modules/bindings/mouse.conf
source = ~/.config/hypr/modules/bindings/apps.conf
source = ~/.config/hypr/modules/bindings/wm.conf
source = ~/.config/hypr/modules/bindings/workspaces.conf
