# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄
exec-once = dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland NO_AT_BRIDGE=1 DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID DBUS_SESSION_BUS_WINDOWID
exec-once = wl-clipboard-history -t
exec-once = hyprpaper
exec-once = gentoo-pipewire-launcher
exec-once = udiskie
exec-once = hypridle
exec-once = mako
exec-once = waybar
exec-once = ~/.config/hypr/xdg-portal-hyprland
exec = gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Dark-Compact"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
