# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█
dwindle {
  force_split=2
  smart_split=true
}

master {
  mfact = 0.6
  special_scale_factor = 0.9
  new_on_top = true
  orientation = left
  new_status = inherit
  allow_small_split = true
}

plugin {
    hyprscrolling {
        column_width = 0.65
        fullscreen_on_one_column = false
    }
}
