# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█
windowrulev2 = float,class:.*(hyprland-share-picker).*
windowrulev2 = float,class:.*(perilous_path).*
windowrulev2 = float,title:.*(Show Me The Key).*
windowrulev2 = float,title:.*(Extension: \(Browserpass\)).*
windowrulev2 = pin,title:.*(Floating Window - Show Me The Key).*
windowrulev2 = opacity 0.98 0.85 override,class:.*(ghostty).*
windowrule = float, title:.*(Open File).*
