# vim:ft=kitty

## name: Harmonious
## license: MIT
## author: samflores
## upstream: https://github.com/samflores/
## blurb: 
#

background           #181316
foreground           #ffffff

cursor               #ffffff
cursor_text_color    #181316

selection_foreground #000000
selection_background #393939

url_color            #be95ff

color0               #C06868
color8               #C06868

color1               #4C753B
color9               #60914A

color2               #7F6712
color10              #9D8018

color3               #316E9F
color11              #3E88C5

color4               #735DA1
color12              #8F74C7

color5               #97526A
color13              #BB6784

color6               #177768
color14              #1E9481

color7               #F6F2F7
color15              #ffffff

color233             #161616
