# vim:ft=kitty

## name: Oxocarbon
## license: MIT
## author: samflores
## upstream: https://github.com/samflores/
## blurb: 
#

background           #161616
foreground           #ffffff

cursor               #ffffff
cursor_text_color    #161616

selection_foreground #000000
selection_background #393939

url_color            #be95ff

color0               #262626
color8               #393939

color1               #ee5396
color9               #ee5396

color2               #42be65
color10              #42be65

color3               #ffe97b
color11              #ffe97b

color4               #33b1ff
color12              #33b1ff

color5               #ff7eb6
color13              #ff7eb6

color6               #3ddbd9
color14              #3ddbd9

color7               #dde1e6
color15              #ffffff

color233             #161616
