unbind C-z

bind -n M-Up copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
# bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

bind -n M-n select-window -n
bind -n M-p select-window -p

bind -n C-S-Left swap-window -t -1\; select-window -t -1
bind -n C-S-Right swap-window -t +1\; select-window -t +1

bind -n M-C-n switch-client -n
bind -n M-C-p switch-client -p

# bind Tab choose-tree -GswZ
unbind w

# bind "'" choose-tree -Zs
unbind s

unbind %
bind v split-window -h -c '#{pane_current_path}'

unbind '"'
bind s split-window -v -c '#{pane_current_path}'

unbind c
bind + new-window -c '#{pane_current_path}'
bind Space command-prompt -p "Project:" "new-window -n %1 \; send-keys '~' %1 Enter"

bind C-l clear-history \; send-keys 'C-l' \; send-keys 'C-l'

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloading configs..."

bind J resize-pane -Z \; select-pane -D
bind K select-pane -U \; resize-pane -Z

bind Enter popup -w '80%' -h '80%' -E

bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""
