set -g prefix 'C-q'
set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-ghostty:extkeys"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
setw -g mode-keys vi
set -s escape-time 0
set -g set-titles on
set -g set-titles-string "#W"
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -s set-clipboard off
set -g status-interval 5
set -gq allow-passthrough on
set -g popup-border-lines rounded
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g extended-keys on
set -g extended-keys-format csi-u
